// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKnzk4vOI6ExU-mA4UM34v3Mg2vVBtVK4',
    appId: '1:72211425276:web:29116ec253d3ba66373479',
    messagingSenderId: '72211425276',
    projectId: 'fztio-f56a4',
    authDomain: 'fztio-f56a4.firebaseapp.com',
    storageBucket: 'fztio-f56a4.appspot.com',
    measurementId: 'G-VK3PQ6HLYN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKKhrAzO9ElluZM5JF_iCqKfduHG3ctRg',
    appId: '1:72211425276:android:167dc2f2d8da50eb373479',
    messagingSenderId: '72211425276',
    projectId: 'fztio-f56a4',
    storageBucket: 'fztio-f56a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCejBbOtTxZ11CZ0DuDh15q5AXQVqMS4jM',
    appId: '1:72211425276:ios:99dc912351889d19373479',
    messagingSenderId: '72211425276',
    projectId: 'fztio-f56a4',
    storageBucket: 'fztio-f56a4.appspot.com',
    iosBundleId: 'com.example.fzt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCejBbOtTxZ11CZ0DuDh15q5AXQVqMS4jM',
    appId: '1:72211425276:ios:99dc912351889d19373479',
    messagingSenderId: '72211425276',
    projectId: 'fztio-f56a4',
    storageBucket: 'fztio-f56a4.appspot.com',
    iosBundleId: 'com.example.fzt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKnzk4vOI6ExU-mA4UM34v3Mg2vVBtVK4',
    appId: '1:72211425276:web:8002a0c2b3526846373479',
    messagingSenderId: '72211425276',
    projectId: 'fztio-f56a4',
    authDomain: 'fztio-f56a4.firebaseapp.com',
    storageBucket: 'fztio-f56a4.appspot.com',
    measurementId: 'G-0THCHN9XEX',
  );
}
